### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by Jonnyan404** [ahui2016/uglynotes#1]
1. 问题一:
`Cannot GET /export`

2. 问题二:
`http://127.0.0.1:10088`即使改了配置`0.0.0.0`,依然显示127

3. 问题三:
- 数据生成目录,建议改为当前运行目录(比如在当前执行目录下有个data文件夹,用来存放db等文件),而不是生成在用户home文件夹下
- 而且配置文件无法指定绝对路径来更改数据生成目录

**Comment by ahui2016** [comment]
感谢反馈！
1. 升级新版修复问题一，关于新版请看 https://github.com/ahui2016/uglynotes/blob/main/Releases.md
2. 这一项配置的效果是由后端框架 (https://gofiber.io) 决定的，其中的细节我也不清楚，也没有能力去改。一般建议用 127.0.0.1:XXX, 然后外面套一层 nginx 或 caddy.
3. 我后续改一下。

**Comment by Jonnyan404** [comment]
> 感谢反馈！
> 
> 1. 升级新版修复问题一，关于新版请看 https://github.com/ahui2016/uglynotes/blob/main/Releases.md
> 2. 这一项配置的效果是由后端框架 (https://gofiber.io) 决定的，其中的细节我也不清楚，也没有能力去改。一般建议用 127.0.0.1:XXX, 然后外面套一层 nginx 或 caddy.
> 3. 我后续改一下。

嗯,等你改好了,我打个包~

**Comment by ahui2016** [comment]
OK, 现在可以指定相对路径，也可以指定绝对路径作为数据库文件夹了，详见 https://github.com/ahui2016/uglynotes/blob/main/Releases.md

**Comment by Jonnyan404** [comment]
> OK, 现在可以指定相对路径，也可以指定绝对路径作为数据库文件夹了，详见 https://github.com/ahui2016/uglynotes/blob/main/Releases.md

-config  和 -dir 可以同时使用的吧?

**Comment by Jonnyan404** [comment]
> OK, 现在可以指定相对路径，也可以指定绝对路径作为数据库文件夹了，详见 https://github.com/ahui2016/uglynotes/blob/main/Releases.md

或者说,我直接修改setting.json里的数据库文件夹配置是否可以?

**Comment by ahui2016** [comment]
-config 和 -dir 可以同时使用，-dir 的优先度更高。settings.json 里那个还是保留原来的功能，需要指定 $HOME 以外的目录时只能使用 -dir 来指定。

**Comment by Jonnyan404** [comment]
o,懂了,直接忽略配置文件目录了.

**Comment by ahui2016** [comment]
本来我也想改成在 settings.json 里设置绝对路径，但发现在 json 里有斜杠等各种特殊字符需要转义，容易出错，还不如在命令行搞更方便一些。
